# Generated by Django 5.1.2 on 2024-10-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
    ]
